### ISSUE TITLE
Error when exporting edited splat

### ISSUE THREAD

**Issue by timhc22** [ReshotAI/gaussian-splatting-blender-addon#10]
Getting the following error when trying to export a splat which I edited, any ideas?

```
Python: Traceback (most recent call last):
  File "/Users/me/Library/Application Support/Blender/3.4/scripts/addons/blender-addon/__init__.py", line 1075, in execute
    xyz[i] = position_attr.data[i].vector.to_tuple()
AttributeError: 'NoneType' object has no attribute 'data'
Python: Traceback (most recent call last):
  File "/Users/me/Library/Application Support/Blender/3.4/scripts/addons/blender-addon/__init__.py", line 1075, in execute
    xyz[i] = position_attr.data[i].vector.to_tuple()
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by MikeTkachuk** [comment]
Hi
1) latest version of the add-on currently only works with blender 4.0+ 
2) apart from 1) it is weird that your object does not have position attribute since it is in-built
3) keep in mind that export works incorrectly with edited scenes. the fix is currently under review
